package com.rookie.webwatch.dto;

public enum ErrorCode {
    FIND_CATEGORY_ERROR, GET_CATEGORY_ERROR, ADD_CATEGORY_ERROR, UPDATE_CATEGORY_ERROR, DELETE_CATEGORY_ERROR,
    FIND_PRODUCT_ERROR, GET_PRODUCT_ERROR, ADD_PRODUCT_ERROR, UPDATE_PRODUCT_ERROR, DELETE_PRODUCT_ERROR
}
